import { ClientNavLink } from "./components/clientNavLink";
import "./styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body>
        <nav className="flex items-center justify-center gap-4 p-1">
          <ClientNavLink href="/">Home</ClientNavLink>
          <ClientNavLink href="/nested">Nested</ClientNavLink>
        </nav>
        <main>{children}</main>
        <footer className="p-1">Global Footer</footer>
      </body>
    </html>
  );
}
